### ISSUE TITLE
The bot pop 801 not 800

### ISSUE THREAD

**Issue by ammarsufyan** [euseanwoon2016/best-popcat-bot#1]
I calculate manually the counter and bot pop 800 + 1 every 30 sec. One more question, we can use this in any region, right? 

before pop:
![image](https://user-images.githubusercontent.com/63483228/129761014-5b2916a8-a5b9-441e-abdb-f4b266017b9d.png)

after pop:
![image](https://user-images.githubusercontent.com/63483228/129761064-32278c9d-a839-4a79-8c20-e7d2658d9e87.png)

**Comment by ammarsufyan** [comment]
> I calculate manually the counter and bot pop 800 + 1 every 30 sec. One more question, this is not region lock right?

Also, can u add console.log to the console so we can track it?

*I'm using a browser version

**Comment by euseanwoon2016** [comment]
> I calculate manually the counter and bot pop 800 + 1 every 30 sec. One more question, we can use this in any region, right? 
> 
> before pop:
> ![image](https://user-images.githubusercontent.com/63483228/129761014-5b2916a8-a5b9-441e-abdb-f4b266017b9d.png)
> 
> after pop:
> ![image](https://user-images.githubusercontent.com/63483228/129761064-32278c9d-a839-4a79-8c20-e7d2658d9e87.png)
> 
> 

Actually, getting sent to the server is 800, u can check in network tab of your browser, but yeah the calculation is 800 + 1, which is wrong. Thanks for letting me know. I will update soon.

**Comment by euseanwoon2016** [comment]
I updated the code in the README.md to apply this fix. Please take a look.
